### ISSUE TITLE
Integrating stop function in FHEM

### ISSUE THREAD

**Issue by 404frank** [dasoho/fernotron-control#2]
Perfekter Code, der jetzt meine Rollanden steuert. Danke dafür. 
Frage mich nur, wie ich die Stop Funktion in FHEM integriere. Das Skript sieht es vor mit dem Schalter "s". Leider funktioniert der Define Befehl in FHEM nicht mit dem Schalter.

**Comment by dasoho** [comment]
Die Restriktion liegt in der Implementierung des FHEM Moduls GenShellSwitch.pm.
Diese Modul erlaubt für die Definition eines generischen Schalters nur zwei Zustände (On, Off) die ich auf Up bzw. Down abgebildet habe. Um noch Stop hinzuzunehmen müsste das Modul GenShellSwitch.pm erweitert werden
