### ISSUE TITLE
Message length issue

### ISSUE THREAD

**Issue by aircutter** [dasoho/fernotron-control#3]
Hi,

I tied to implement your code with the recommendend devices on my Rasperry FHEM setup. So far so good. 

But when I sniff the Remote with the Sniffer it returns the message that the code received is only 277 long instead of the expected 280.

I tried to find a solution in the code but it seems that I miss context from Fernotron to be able to fix it.

Any advice?

**Comment by pete1pete** [comment]
Hi, 
 I modified the code by disabling the length check of the received code and this worked for me

void Fernotron::send(char* code) {
  if (nTransmitterPin == -1) {
    printf("Transmit mode not enabled\n");
    return; 
  }
**/* ==>comment out  to bypass length check
  else if (strlen(code) != FERNOTRON_PROTOCOL_LENGTH) {
     printf("Input code has wrong length.  Input: %d,  Expected: %d\n", strlen(code), FERNOTRON_PROTOCOL_LENGTH);
    return; 
  }
<== end of my comment. */**
  else {
    int highLength = 0;
    int lowLength = 0;

    for (int r = 0; r < nRepeatTransmit; r++) {
**/* ==> comment out  to bypass length check
        for(int i = 0; i < FERNOTRON_PROTOCOL_LENGTH; i++) { 
<== end of my comment. */**
        for(int i = 0; i < strlen(code) ; i++) {  
          ....

**Comment by pete1pete** [comment]
sorry, forgot to mention the added line after the second out commented block
  for(int i = 0; i < strlen(code) ; i++) {

**Comment by aircutter** [comment]
Thanks! That worked on the transmit side.

On the recieve side I took again some time today and got it to work as well. Added a rather “dirty” fix. But it work with my shutter system.
if (changeCount + 1 != FERNOTRON_PROTOCOL_LENGTH * 2) {
CHANGED TO
if (changeCount + 3 != FERNOTRON_PROTOCOL_LENGTH * 2) {

then it works
